### PR TITLE
Fix responsiveness for mobile view

### LINKED ISSUE #191: The titles from the job description are unnoticeably small and some sections have no diacritics - mobile
**ENVIRONMENT**

URL: https://oportunitatisicariere.ro/
Browser: Chrome
OS: Android

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Go to "Cum poti ajuta" section
3. Click on any job

**EXPECTED RESULTS:**

The titles are visible and all sections are written with diacritics (where is the case).

**ACTUAL RESULTS:**

The titles are too small and the content of the "Alte informatii (optional)" and "Ce oferim" sections has no diacritics.
ab0f9415-822d-49cb-8e34-62a3bdf5c275 (1)

### PR DESCRIPTION
**Pull request by adriandoinea**
Resolves #191

### CODE REVIEW

**Review by AndreiBarari — COMMENTED** [review]
It looks good
There should be a gap between the navigation bar and the content of the page
A smaller margin bottom for the "Înapoi la locurile de muncă" would improve the visual aspect of that section on larger screens, from 1024px and larger

**Comment by adriandoinea** [comment]
> It looks good
> 
> There should be a gap between the navigation bar and the content of the page
> 
> A smaller margin bottom for the "Înapoi la locurile de muncă" would improve the visual aspect of that section on larger screens, from 1024px and larger
> 
> 

Thanks for the review, Andrei. This PR targets small screens and was intended to change things for the mobile view only. However, if we want these changes for the larger screens they can easily be applied, I just need a confirmation from the team. 
CC: @talidag

**Comment by talidag** [comment]
Thanks guys for the improvements. I've made some additional changes to the design and we can close this issue now.

**Review by AndreiBarari — APPROVED** [review]
It looks good!
All the issues have been addresed!

**Pull request merged**
