### PR TITLE
Fix inconsistent paragraphs width

### LINKED ISSUE #380: Inconsistent paragraph width
There are a few sections in which the width of the paragraphs is not consistent.
The width of the paragraphs should be consistent throughout the website.

Desktop Screenshot 2024 10 16 - 14 42 40 44
Desktop Screenshot 2024 10 16 - 14 36 12 57
Desktop Screenshot 2024 10 16 - 14 37 51 58

### PR DESCRIPTION
**Pull request by adriandoinea**
Resolves #380

### CODE REVIEW

**Comment by AndreiBarari** [comment]
Desktop Screenshot 2024 11 19 - 09 54 23 05
Paragraph in thank you sectio is causing issues on smaller screens
Do not use a fix width, try to use min/max-width or with with clamp property

**Comment by adriandoinea** [comment]
@AndreiBarari fixed. We cannot use min/max-width as that would cause the same situation as we currently have in production (inconsistent width)

**Comment by adriandoinea** [comment]
@AndreiBarari thanks! If I remove that we'll have a width of 866.02px for the paragraphs in that section so it won't really be consistent with the others anymore

**Comment by AndreiBarari** [comment]
@adriandoinea it's ok without the width, it is not the same width as the one bellow it but it is consistent in it's form, on two lines

**Comment by adriandoinea** [comment]
@AndreiBarari alright, I removed it ✅

**Review by AndreiBarari — APPROVED** [review]

**Pull request merged**
